fix: update uv version in github actions (#434)
* fix: bump uv version in CI/CD, add checks for lockfile

* bump uv lockfile

diff --git a/.github/workflows/build-check-test.yml b/.github/workflows/build-check-test.yml
--- a/.github/workflows/build-check-test.yml
+++ b/.github/workflows/build-check-test.yml
@@ -20,10 +20,10 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Install uv
-        uses: astral-sh/setup-uv@v5
+        uses: astral-sh/setup-uv@v6
         with:
-          version: "0.4.x"
-          enable-cache: true
+          version: "0.8.x"
+          enable-cache: false
           cache-dependency-glob: "uv.lock"
           python-version: ${{ matrix.python-version }}
       - name: Install just
@@ -31,6 +31,9 @@ jobs:
       - name: Install dependencies
         run: |
           just install
+      - name: Check uv lockfile metadata
+        run: |
+          if ! uv lock --check; then echo "::error::`uv lock --check` has failed, ensure you have the latest `uv` version installed with `uv self update` and run `uv sync`"; exit 1; fi
       - name: Check format
         run: |
           just check-format
